### PR TITLE
ADD CP949 Charset

### PR DESCRIPTION
**Pull request by eyehint**

### CODE REVIEW

**Comment by scandum** [comment]
Thanks, will take a look at it soon.

**Comment by scandum** [comment]
I don't think the way you had CP949TOUTF8 set up worked, so I redid most of that and streamlined some other code while at it.

https://mudhalla.net/tintin-beta.tar.gz

I don't have the address for any korean muds, so it hasn't been tested.

**Comment by eyehint** [comment]
oldmud.shop 9999
It's Korean mud what I do

**Comment by eyehint** [comment]
If you test this run lunux screen and set encoding euc-kr
or set locale euc-kr in linux

**Comment by scandum** [comment]
Looks like it works, should be included with an official release in 1 or 2 months.

**Pull request closed without merging**
